<a href="https://colab.research.google.com/github/mandalivaishnavi/vaishnavi19/blob/main/C_I_E_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df=pd.read_csv('/content/iris.csv')
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [11]:
x=df[['sepal.length','sepal.width','petal.length','petal.width']]
y=df[['variety']]

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)

In [17]:
x_train

    sepal.length  sepal.width  petal.length  petal.width
62           6.0          2.2           4.0          1.0
23           5.1          3.3           1.7          0.5
26           5.0          3.4           1.6          0.4
48           5.3          3.7           1.5          0.2
2            4.7          3.2           1.3          0.2
..           ...          ...           ...          ...
71           6.1          2.8           4.0          1.3
12           4.8          3.0           1.4          0.1
50           7.0          3.2           4.7          1.4
7            5.0          3.4           1.5          0.2
70           5.9          3.2           4.8          1.8

[120 rows x 4 columns]

In [18]:
x_test

     sepal.length  sepal.width  petal.length  petal.width
38            4.4          3.0           1.3          0.2
66            5.6          3.0           4.5          1.5
115           6.4          3.2           5.3          2.3
117           7.7          3.8           6.7          2.2
89            5.5          2.5           4.0          1.3
136           6.3          3.4           5.6          2.4
68            6.2          2.2           4.5          1.5
94            5.6          2.7           4.2          1.3
84            5.4          3.0           4.5          1.5
28            5.2          3.4           1.4          0.2
90            5.5          2.6           4.4          1.2
11            4.8          3.4           1.6          0.2
40            5.0          3.5           1.3          0.3
126           6.2          2.8           4.8          1.8
79            5.7          2.6           3.5          1.0
144           6.7          3.3           5.7          2.5
123           6.3          2.7           4.9          1.8
124           6.7          3.3           5.7          2.1
76            6.8          2.8           4.8          1.4
59            5.2          2.7           3.9          1.4
132           6.4          2.8           5.6          2.2
105           7.6          3.0           6.6          2.1
53            5.5          2.3           4.0          1.3
17            5.1          3.5           1.4          0.3
64            5.6          2.9           3.6          1.3
18            5.7          3.8           1.7          0.3
13            4.3          3.0           1.1          0.1
116           6.5          3.0           5.5          1.8
9             4.9          3.1           1.5          0.1
81            5.5          2.4           3.7          1.0

In [19]:
y_train

       variety
62  Versicolor
23      Setosa
26      Setosa
48      Setosa
2       Setosa
..         ...
71  Versicolor
12      Setosa
50  Versicolor
7       Setosa
70  Versicolor

[120 rows x 1 columns]

In [20]:
y_test

        variety
38       Setosa
66   Versicolor
115   Virginica
117   Virginica
89   Versicolor
136   Virginica
68   Versicolor
94   Versicolor
84   Versicolor
28       Setosa
90   Versicolor
11       Setosa
40       Setosa
126   Virginica
79   Versicolor
144   Virginica
123   Virginica
124   Virginica
76   Versicolor
59   Versicolor
132   Virginica
105   Virginica
53   Versicolor
17       Setosa
64   Versicolor
18       Setosa
13       Setosa
116   Virginica
9        Setosa
81   Versicolor

In [22]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [23]:
y_pred=dtc.predict(x_test)
y_pred

array(['Setosa', 'Versicolor', 'Virginica', 'Virginica', 'Versicolor',
       'Virginica', 'Versicolor', 'Versicolor', 'Versicolor', 'Setosa',
       'Versicolor', 'Setosa', 'Setosa', 'Virginica', 'Versicolor',
       'Virginica', 'Virginica', 'Virginica', 'Versicolor', 'Versicolor',
       'Virginica', 'Virginica', 'Versicolor', 'Setosa', 'Versicolor',
       'Setosa', 'Setosa', 'Virginica', 'Setosa', 'Versicolor'],
      dtype=object)

In [ ]:
from sklearn.matrix import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score
accuracy_score(y_test,y_pred)